# -----------------------------------------------------------------------
# SCPN Fusion Core -- ReadTheDocs Configuration
# Copyright 1998-2026 Miroslav Sotek. All rights reserved.
# License: GNU AGPL v3 | Commercial licensing available
# -----------------------------------------------------------------------
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/sphinx/conf.py

python:
  install:
    - requirements: docs/sphinx/requirements.txt
