# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1

[[annotations]]
path = ["*.md", "*.txt", "*.json", "*.yaml", "*.yml", "*.toml", "*.cfg", "*.ini", "*.lock"]
SPDX-FileCopyrightText = "1998-2026 Miroslav Šotek <protoscience@anulum.li>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["docs/**", "*.png", "*.svg", "*.jpg"]
SPDX-FileCopyrightText = "1998-2026 Miroslav Šotek <protoscience@anulum.li>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["weights/**", "*.npz", "*.npy"]
SPDX-FileCopyrightText = "1998-2026 Miroslav Šotek <protoscience@anulum.li>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
