# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — Artifact Compact Codec Helpers
from __future__ import annotations

import base64
import zlib
from typing import Any, Dict, List, Type


def encode_u64_compact_payload(data_u64: List[int]) -> Dict[str, Any]:
    """Encode uint64 list as zlib-compressed base64 little-endian payload."""
    raw = bytearray()
    for value in data_u64:
        raw.extend(int(value & 0xFFFFFFFFFFFFFFFF).to_bytes(8, "little", signed=False))
    compressed = zlib.compress(bytes(raw), level=9)
    payload = base64.b64encode(compressed).decode("ascii")
    return {
        "encoding": "u64-le-zlib-base64",
        "count": len(data_u64),
        "data_u64_b64_zlib": payload,
    }


def decode_u64_compact_payload(
    encoded: Dict[str, Any],
    *,
    error_type: Type[Exception],
    max_packed_words: int,
    max_compressed_bytes: int,
    max_decompressed_bytes: int,
) -> List[int]:
    """Decode compact uint64 payload generated by ``encode_u64_compact_payload``."""
    if encoded.get("encoding") != "u64-le-zlib-base64":
        raise error_type(f"Unsupported packed encoding: {encoded.get('encoding')}")

    payload = encoded.get("data_u64_b64_zlib")
    if not isinstance(payload, str):
        raise error_type("Missing compact packed payload string.")

    count_val = encoded.get("count")
    if isinstance(count_val, int) and (count_val < 0 or count_val > max_packed_words):
        raise error_type(f"Packed count {count_val} exceeds limit {max_packed_words}.")

    try:
        comp = base64.b64decode(payload.encode("ascii"), validate=True)
    except Exception as exc:
        raise error_type(f"Invalid base64 payload: {exc}") from exc

    if len(comp) > max_compressed_bytes:
        raise error_type(f"Compressed payload too large: {len(comp)} bytes.")

    try:
        decomp = zlib.decompressobj()
        raw = decomp.decompress(comp, max_decompressed_bytes + 1)
        if decomp.unconsumed_tail:
            raise error_type("Decompressed packed payload exceeds configured limit.")
        raw += decomp.flush()
    except error_type:
        raise
    except Exception as exc:
        raise error_type(f"Invalid compact packed payload: {exc}") from exc

    if len(raw) > max_decompressed_bytes:
        raise error_type("Decompressed packed payload exceeds configured limit.")

    if len(raw) % 8 != 0:
        raise error_type(f"Compact packed payload byte-length {len(raw)} is not divisible by 8.")

    available = len(raw) // 8
    if isinstance(count_val, int):
        count = count_val
    elif count_val is None:
        count = available
    else:
        raise error_type(f"Invalid compact packed count type: {type(count_val).__name__}.")
    if count < 0 or count > available:
        raise error_type(f"Invalid compact packed count {count}; available words={available}.")

    return [int.from_bytes(raw[i * 8 : (i + 1) * 8], "little", signed=False) for i in range(count)]


__all__ = ["encode_u64_compact_payload", "decode_u64_compact_payload"]
