# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — stale-artifact guard binding tracked evidence JSONs to their generators
"""Stale-artifact guard: tracked evidence JSONs must match the generator that made them.

Each tracked validation artefact records ``provenance.generator_sha256`` (the digest of its
generator script at generation time). These tests recompute the digest of the CURRENT
generator source and fail when they diverge — i.e. when someone edits a generator without
regenerating (and re-committing) its artefact, or edits a tracked artefact by hand. The
distinct-eye finding F2 on the real-data evidence lane.

Hermetic: pure file reads + hashing, no scientific dependencies.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]

# (tracked artefact, generator that must have produced it)
_BOUND_PAIRS = [
    (
        "artifacts/real_diiid_145419/real_145419_validation.json",
        "validation/validate_real_diiid_145419.py",
    ),
    (
        "artifacts/coilgrad_adjoint_fd_evidence.json",
        "validation/measure_coilgrad_adjoint_fd.py",
    ),
    (
        "artifacts/rung2_mg_preconditioner/iteration_counts.json",
        "validation/measure_mg_preconditioner_iterations.py",
    ),
]


@pytest.mark.parametrize(("artifact_rel", "generator_rel"), _BOUND_PAIRS)
def test_tracked_artifact_matches_its_generator(artifact_rel: str, generator_rel: str) -> None:
    artifact = REPO / artifact_rel
    generator = REPO / generator_rel
    assert generator.exists(), f"generator missing: {generator_rel}"
    assert artifact.exists(), f"tracked artefact missing: {artifact_rel}"
    record = json.loads(artifact.read_text())
    recorded = record.get("provenance", {}).get("generator_sha256") or record.get(
        "generator_sha256"
    )
    assert recorded, (
        f"{artifact_rel} lacks a generator_sha256 provenance field — regenerate it with the "
        "current generator"
    )
    current = hashlib.sha256(generator.read_bytes()).hexdigest()
    assert recorded == current, (
        f"{artifact_rel} is STALE: it was generated by {generator_rel}@{recorded[:12]} but the "
        f"current generator is @{current[:12]} — rerun the generator and commit both together"
    )


def test_artifacts_have_environment_provenance() -> None:
    """The real-data artefact must state the exact package versions that produced it."""
    record = json.loads((REPO / _BOUND_PAIRS[0][0]).read_text())
    packages = record["provenance"]["packages"]
    for name in ("omas", "freeqdsk", "numpy", "scipy", "jax"):
        assert packages.get(name), f"missing package version in provenance: {name}"
    assert record["provenance"].get("pinned_requirements_sha256")
