# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — stale-artifact guard binding tracked evidence JSONs to their generators
"""Stale-artifact guard: tracked evidence JSONs must match the generator that made them.

Each tracked validation artefact records ``provenance.generator_sha256`` (the digest of its
generator script at generation time). These tests recompute the digest of the CURRENT
generator source and fail when they diverge — i.e. when someone edits a generator without
regenerating (and re-committing) its artefact, or edits a tracked artefact by hand. The
distinct-eye finding F2 on the real-data evidence lane.

Hermetic: pure file reads + hashing, no scientific dependencies.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]

# (tracked artefact, generator that must have produced it)
_BOUND_PAIRS = [
    (
        "artifacts/real_diiid_145419/real_145419_validation.json",
        "validation/validate_real_diiid_145419.py",
    ),
    (
        "artifacts/coilgrad_adjoint_fd_evidence.json",
        "validation/measure_coilgrad_adjoint_fd.py",
    ),
    (
        "artifacts/rung2_mg_preconditioner/iteration_counts.json",
        "validation/measure_mg_preconditioner_iterations.py",
    ),
    (
        "artifacts/rung2_mg_preconditioner/compiled_forward_speedup.json",
        "validation/measure_compiled_forward_speedup.py",
    ),
    (
        "artifacts/rung2_mg_preconditioner/warm_start_forward.json",
        "validation/measure_warm_start_forward.py",
    ),
    (
        "artifacts/rung2_mg_preconditioner/batched_forward_amortisation.json",
        "validation/measure_batched_forward.py",
    ),
    (
        "artifacts/disruption_transfer_generalization.json",
        "validation/benchmark_disruption_transfer_generalization.py",
    ),
    (
        "artifacts/disruption_threshold_sweep.json",
        "tools/sweep_disruption_threshold.py",
    ),
    (
        "artifacts/disruption_roc_curve.json",
        "tools/sweep_disruption_threshold.py",
    ),
]

_DISRUPTION_DEPENDENCIES = {
    "artifacts/disruption_transfer_generalization.json": (
        "validation/validate_real_shots.py",
        "src/scpn_fusion/control/disruption_predictor.py",
    ),
    "artifacts/disruption_threshold_sweep.json": (
        "src/scpn_fusion/control/disruption_predictor.py",
    ),
    "artifacts/disruption_roc_curve.json": ("src/scpn_fusion/control/disruption_predictor.py",),
}
_DISRUPTION_DATA = REPO / "validation" / "reference_data" / "diiid" / "disruption_shots"


def _digest_paths(paths: tuple[Path, ...]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: item.as_posix()):
        label = path.relative_to(REPO).as_posix()
        digest.update(label.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


@pytest.mark.parametrize(("artifact_rel", "generator_rel"), _BOUND_PAIRS)
def test_tracked_artifact_matches_its_generator(artifact_rel: str, generator_rel: str) -> None:
    artifact = REPO / artifact_rel
    generator = REPO / generator_rel
    assert generator.exists(), f"generator missing: {generator_rel}"
    assert artifact.exists(), f"tracked artefact missing: {artifact_rel}"
    record = json.loads(artifact.read_text())
    recorded = record.get("provenance", {}).get("generator_sha256") or record.get(
        "generator_sha256"
    )
    assert recorded, (
        f"{artifact_rel} lacks a generator_sha256 provenance field — regenerate it with the "
        "current generator"
    )
    current = hashlib.sha256(generator.read_bytes()).hexdigest()
    assert recorded == current, (
        f"{artifact_rel} is STALE: it was generated by {generator_rel}@{recorded[:12]} but the "
        f"current generator is @{current[:12]} — rerun the generator and commit both together"
    )


def test_artifacts_have_environment_provenance() -> None:
    """The real-data artefact must state the exact package versions that produced it."""
    record = json.loads((REPO / _BOUND_PAIRS[0][0]).read_text())
    packages = record["provenance"]["packages"]
    for name in ("omas", "freeqdsk", "numpy", "scipy", "jax"):
        assert packages.get(name), f"missing package version in provenance: {name}"
    assert record["provenance"].get("pinned_requirements_sha256")


@pytest.mark.parametrize(("artifact_rel", "_generator_rel"), _BOUND_PAIRS)
def test_tracked_artifact_matches_pinned_requirements(
    artifact_rel: str, _generator_rel: str
) -> None:
    """Every bound artifact records the current hash-pinned environment contract.

    After a lock refresh, regenerate all bound artifacts from the repository root with::

        PINNED_PY=/media/anulum/GOTM/_scratch/fusion-pinned-venv2/bin/python
        PYTHONPATH=src:. $PINNED_PY validation/validate_real_diiid_145419.py
        PYTHONPATH=src:. $PINNED_PY validation/measure_coilgrad_adjoint_fd.py
        PYTHONPATH=src:. $PINNED_PY validation/measure_mg_preconditioner_iterations.py
        PYTHONPATH=src:. $PINNED_PY validation/measure_batched_forward.py
        PYTHONPATH=src:. $PINNED_PY validation/benchmark_disruption_transfer_generalization.py --strict
        PYTHONPATH=src:. $PINNED_PY tools/sweep_disruption_threshold.py
    """
    artifact = json.loads((REPO / artifact_rel).read_text(encoding="utf-8"))
    recorded = artifact.get("provenance", {}).get("pinned_requirements_sha256")
    current = hashlib.sha256((REPO / "requirements" / "full.txt").read_bytes()).hexdigest()
    assert recorded == current, (
        f"{artifact_rel} is not bound to the current requirements/full.txt: "
        f"recorded={recorded!r}, current={current}. See this test's docstring for the exact "
        "pinned-venv regeneration commands."
    )


@pytest.mark.parametrize(("artifact_rel", "dependency_rels"), _DISRUPTION_DEPENDENCIES.items())
def test_disruption_artifact_matches_logic_and_data_corpus(
    artifact_rel: str, dependency_rels: tuple[str, ...]
) -> None:
    """Disruption evidence becomes stale when logic or its NPZ corpus changes."""
    artifact = json.loads((REPO / artifact_rel).read_text(encoding="utf-8"))
    provenance = artifact["provenance"]
    dependencies = tuple(REPO / rel for rel in dependency_rels)
    data_files = tuple(_DISRUPTION_DATA.glob("*.npz"))

    assert provenance["logic_sources"] == list(dependency_rels)
    assert provenance["logic_sources_sha256"] == _digest_paths(dependencies)
    assert provenance["disruption_data_file_count"] == len(data_files)
    assert provenance["disruption_data_sha256"] == _digest_paths(data_files)
