name: Bug Report
description: Report a bug in SCPN Fusion Core
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. If the bug involves incorrect
        physics output, you **must** include a reference paper and
        equation number so the team can verify the expected behaviour.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Minimal steps to reproduce the issue.
      placeholder: |
        1. Install: `pip install -e .`
        2. Run: `python -m pytest tests/test_xxx.py -k test_yyy`
        3. Observe: ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened. Include error messages and tracebacks.
    validations:
      required: true
  - type: textarea
    id: physics-reference
    attributes:
      label: Physics Reference (required for physics bugs)
      description: |
        If this bug involves incorrect physics output (wrong TBR,
        unrealistic Q, bad equilibrium, etc.), cite the reference paper,
        equation, and expected value. For non-physics bugs (crashes,
        import errors, UI issues), write "N/A — not a physics bug."
      placeholder: "Author(s) Year (DOI/arXiv), Eq. N — expected value"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Ubuntu 22.04+
        - Windows 11
        - macOS 14+
        - Other (specify in Additional Context)
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "3.11.5"
    validations:
      required: true
  - type: input
    id: scpn-version
    attributes:
      label: scpn-fusion Version
      placeholder: "3.1.0"
    validations:
      required: true
  - type: dropdown
    id: rust
    attributes:
      label: sc-neurocore (Rust) installed?
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context (config files, screenshots, related issues).
    validations:
      required: false
