# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — TGLF Interface Runtime
"""Runtime subprocess helpers for the public TGLF interface."""

from __future__ import annotations

import logging
import math
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from scpn_fusion.core._tglf_interface_types import (
    TGLFInputDeck,
    TGLFOutput,
    _TGLF_MAX_RETRIES_LIMIT,
    _TGLF_RETRY_BACKOFF_SECONDS,
)

logger = logging.getLogger(__name__)

_DEUTERIUM_MASS_KG = 2.0 * 1.67262192369e-27
_ELEMENTARY_CHARGE_C = 1.602176634e-19


def _normalize_tglf_timeout_seconds(timeout_s: float) -> float:
    timeout = float(timeout_s)
    if not math.isfinite(timeout) or timeout <= 0.0:
        raise ValueError("timeout_s must be finite and > 0.")
    return timeout


def _normalize_tglf_max_retries(max_retries: int) -> int:
    if isinstance(max_retries, bool) or not isinstance(max_retries, int):
        raise ValueError(f"max_retries must be an integer in [0, {_TGLF_MAX_RETRIES_LIMIT}].")
    retries = int(max_retries)
    if retries < 0 or retries > _TGLF_MAX_RETRIES_LIMIT:
        raise ValueError(f"max_retries must be an integer in [0, {_TGLF_MAX_RETRIES_LIMIT}].")
    return retries


def _validate_tglf_command_name(command: str = "tglf") -> str:
    """Return a normalized command name after enforcing the PATH-only contract."""
    if not isinstance(command, str) or not command.strip():
        raise ValueError("TGLF command must be a non-empty PATH command name.")
    command = command.strip()
    if Path(command).name != command or "/" in command or "\\" in command:
        raise ValueError("TGLF must be resolved through PATH; filesystem paths are forbidden.")
    return command


def _resolve_tglf_command(command: str = "tglf") -> str:
    """Resolve a validated command name through ``PATH``."""
    command = _validate_tglf_command_name(command)
    resolved = shutil.which(command)
    if resolved is None:
        raise FileNotFoundError(f"TGLF command not found on PATH: {command}")
    return resolved


def _validate_tglf_deck(deck: TGLFInputDeck) -> None:
    """Reject non-finite or physically invalid values before external execution."""
    for field_name, value in deck.__dict__.items():
        if isinstance(value, (float, int)) and not np.isfinite(value):
            raise ValueError(f"TGLF input {field_name!r} must be finite; got {value!r}.")
    positive = {
        "q": deck.q,
        "kappa": deck.kappa,
        "T_e_keV": deck.T_e_keV,
        "T_i_keV": deck.T_i_keV,
        "R_major": deck.R_major,
        "a_minor": deck.a_minor,
        "B_toroidal": deck.B_toroidal,
    }
    for field_name, value in positive.items():
        if value <= 0.0:
            raise ValueError(f"TGLF input {field_name!r} must be > 0; got {value!r}.")
    if not 0.0 < deck.rho <= 1.0:
        raise ValueError(f"TGLF input 'rho' must be in (0, 1]; got {deck.rho!r}.")
    if deck.beta_e < 0.0 or deck.xnue < 0.0 or deck.Z_eff < 1.0:
        raise ValueError("TGLF beta_e/xnue must be non-negative and Z_eff must be >= 1.")


def render_tglf_input(deck: TGLFInputDeck) -> str:
    """Render a current GACODE ``input.tglf`` key-value deck.

    Public SCPN inputs use ``R/L`` gradients; GACODE TGLF consumes ``a/L``.
    Species 1 is the electron and species 2 is a deuterium main ion, matching
    current GACODE defaults and output ordering.
    """
    _validate_tglf_deck(deck)
    a_over_r = deck.a_minor / deck.R_major
    rmin_loc = deck.rho
    rmaj_loc = deck.R_major / deck.a_minor
    q_prime_loc = (
        deck.q_prime_loc if deck.q_prime_loc != 0.0 else deck.s_hat * (deck.q / rmin_loc) ** 2
    )
    p_prime_loc = (
        deck.p_prime_loc
        if deck.p_prime_loc != 0.0
        else -deck.alpha_mhd / (8.0 * math.pi * deck.q * rmaj_loc * rmin_loc)
    )
    lines = [
        "# TGLF input deck generated by SCPN Fusion Core",
        f"# rho = {deck.rho:.6f}",
        "UNITS = GYRO",
        "USE_TRANSPORT_MODEL = .true.",
        "GEOMETRY_FLAG = 1",
        f"USE_BPER = {'.true.' if deck.use_bper else '.false.'}",
        f"USE_BPAR = {'.true.' if deck.use_bpar else '.false.'}",
        "SIGN_BT = 1.0",
        "SIGN_IT = 1.0",
        "NS = 2",
        "MASS_1 = 2.723000e-4",
        "MASS_2 = 1.0",
        "ZS_1 = -1.0",
        "ZS_2 = 1.0",
        f"RLNS_1 = {deck.R_Lne * a_over_r:.12g}",
        f"RLNS_2 = {deck.R_Lni * a_over_r:.12g}",
        f"RLTS_1 = {deck.R_LTe * a_over_r:.12g}",
        f"RLTS_2 = {deck.R_LTi * a_over_r:.12g}",
        "TAUS_1 = 1.0",
        f"TAUS_2 = {deck.T_i_keV / deck.T_e_keV:.12g}",
        "AS_1 = 1.0",
        "AS_2 = 1.0",
        f"Q_LOC = {deck.q:.12g}",
        f"Q_PRIME_LOC = {q_prime_loc:.12g}",
        f"P_PRIME_LOC = {p_prime_loc:.12g}",
        f"S_KAPPA_LOC = {deck.s_kappa:.12g}",
        f"S_DELTA_LOC = {deck.s_delta:.12g}",
        f"KAPPA_LOC = {deck.kappa:.12g}",
        f"DELTA_LOC = {deck.delta:.12g}",
        f"XNUE = {deck.xnue:.12g}",
        f"BETAE = {deck.beta_e:.12g}",
        f"ZEFF = {deck.Z_eff:.12g}",
        f"RMAJ_LOC = {rmaj_loc:.12g}",
        f"RMIN_LOC = {rmin_loc:.12g}",
    ]
    return "\n".join(lines) + "\n"


def write_tglf_input_file(deck: TGLFInputDeck, output_dir: str | Path) -> Path:
    """Write a validated current-GACODE ``input.tglf`` file."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "input.tglf"
    path.write_text(render_tglf_input(deck), encoding="utf-8")
    return path


def _gyro_bohm_diffusivity(deck: TGLFInputDeck) -> float:
    """Return the GACODE ``rho_s^2 c_s / a`` diffusivity scale in ``m^2/s``."""
    te_joule = deck.T_e_keV * 1.0e3 * _ELEMENTARY_CHARGE_C
    sound_speed = math.sqrt(te_joule / _DEUTERIUM_MASS_KG)
    rho_s = _DEUTERIUM_MASS_KG * sound_speed / (_ELEMENTARY_CHARGE_C * deck.B_toroidal)
    return rho_s * rho_s * sound_speed / deck.a_minor


def _effective_coefficient(flux_gb: float, gradient_a_over_l: float, chi_gb: float) -> float:
    """Convert signed gyro-Bohm flux to a gradient-normalised coefficient."""
    if abs(gradient_a_over_l) <= 1.0e-12:
        if abs(flux_gb) <= 1.0e-12:
            return 0.0
        raise RuntimeError("TGLF emitted finite flux for a zero normalising gradient.")
    return flux_gb * chi_gb / gradient_a_over_l


def _load_numeric_rows(path: Path, *, skiprows: int) -> NDArray[np.float64]:
    """Load a finite, non-empty numeric TGLF table with stable 2-D shape."""
    try:
        data = np.loadtxt(path, skiprows=skiprows, ndmin=2)
    except (OSError, ValueError) as exc:
        raise RuntimeError(f"Could not parse TGLF output {path.name}: {exc}") from exc
    out = np.asarray(data, dtype=np.float64)
    if out.size == 0 or not bool(np.all(np.isfinite(out))):
        raise RuntimeError(f"TGLF output {path.name} is empty or non-finite.")
    return out


def _parse_gacode_tglf_output(output_dir: Path, deck: TGLFInputDeck) -> TGLFOutput:
    """Parse current GACODE flux and eigenvalue files for a completed run."""
    flux_path = output_dir / "out.tglf.gbflux"
    eigen_path = output_dir / "out.tglf.eigenvalue_spectrum"
    flux = _load_numeric_rows(flux_path, skiprows=0).reshape(-1)
    if flux.size < 4:
        raise RuntimeError("TGLF out.tglf.gbflux must contain at least four values.")
    particle_e = float(flux[0])
    particle_i = float(flux[1])
    q_e = float(flux[2])
    q_i = float(flux[3])

    eigen = _load_numeric_rows(eigen_path, skiprows=2)
    if eigen.shape[1] < 2 or eigen.shape[1] % 2 != 0:
        raise RuntimeError("TGLF eigenvalue spectrum must contain gamma/frequency pairs.")
    gamma_max = float(np.max(eigen[:, 0::2]))

    a_over_r = deck.a_minor / deck.R_major
    chi_gb = _gyro_bohm_diffusivity(deck)
    chi_i = _effective_coefficient(q_i, deck.R_LTi * a_over_r, chi_gb)
    chi_e = _effective_coefficient(q_e, deck.R_LTe * a_over_r, chi_gb)
    d_e = _effective_coefficient(particle_e, deck.R_Lne * a_over_r, chi_gb)
    d_i = _effective_coefficient(particle_i, deck.R_Lni * a_over_r, chi_gb)
    return TGLFOutput(
        rho=deck.rho,
        chi_i=chi_i,
        chi_e=chi_e,
        gamma_max=gamma_max,
        q_i=q_i,
        q_e=q_e,
        particle_e=particle_e,
        particle_i=particle_i,
        d_e=d_e,
        d_i=d_i,
    )


def _parse_gacode_tglf_spectrum(
    output_dir: Path,
) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    """Return per-``ky`` dominant ``(gamma, frequency, ky)`` arrays."""
    eigen = _load_numeric_rows(output_dir / "out.tglf.eigenvalue_spectrum", skiprows=2)
    ky = _load_numeric_rows(output_dir / "out.tglf.ky_spectrum", skiprows=2).reshape(-1)
    if eigen.shape[1] < 2 or eigen.shape[1] % 2 != 0:
        raise RuntimeError("TGLF eigenvalue spectrum must contain gamma/frequency pairs.")
    if eigen.shape[0] != ky.size:
        raise RuntimeError("TGLF ky and eigenvalue spectra have inconsistent row counts.")
    gamma_modes = eigen[:, 0::2]
    frequency_modes = eigen[:, 1::2]
    dominant = np.argmax(gamma_modes, axis=1)
    rows = np.arange(eigen.shape[0])
    gamma = np.asarray(gamma_modes[rows, dominant], dtype=np.float64)
    frequency = np.asarray(frequency_modes[rows, dominant], dtype=np.float64)
    return gamma, frequency, np.asarray(ky, dtype=np.float64)


def run_tglf_binary(
    deck: TGLFInputDeck,
    *,
    tglf_command: str = "tglf",
    timeout_s: float = 120.0,
    work_dir: str | Path | None = None,
    max_retries: int = 2,
) -> TGLFOutput:
    """Execute PATH-resolved GACODE TGLF and parse its current output files."""
    timeout_s = _normalize_tglf_timeout_seconds(timeout_s)
    max_retries = _normalize_tglf_max_retries(max_retries)
    tglf_path = _resolve_tglf_command(tglf_command)
    _validate_tglf_deck(deck)

    cleanup = False
    if work_dir is None:
        work_dir = Path(tempfile.mkdtemp(prefix="tglf_"))
        cleanup = True
    else:
        work_dir = Path(work_dir)
        work_dir.mkdir(parents=True, exist_ok=True)

    last_exc: Exception | None = None
    try:
        for attempt in range(max_retries + 1):
            last_exc = None
            try:
                for stale in work_dir.glob("out.tglf.*"):
                    if stale.is_file():
                        stale.unlink()
                write_tglf_input_file(deck, work_dir)
                result = subprocess.run(
                    [tglf_path, "-e", "."],
                    cwd=str(work_dir),
                    capture_output=True,
                    text=True,
                    timeout=timeout_s,
                )

                if result.returncode != 0:
                    raise RuntimeError(
                        f"TGLF exited with code {result.returncode}: {result.stderr[:500]}"
                    )

                return _parse_gacode_tglf_output(work_dir, deck)
            except (RuntimeError, subprocess.TimeoutExpired) as exc:
                last_exc = exc
                if attempt < max_retries:
                    logger.warning("TGLF attempt %d failed: %s. Retrying...", attempt + 1, exc)
                    import time

                    time.sleep(_TGLF_RETRY_BACKOFF_SECONDS)
        assert last_exc is not None
        raise RuntimeError(f"TGLF execution failed after {max_retries + 1} attempts.") from last_exc
    finally:
        if cleanup:
            shutil.rmtree(work_dir, ignore_errors=True)


def _parse_tglf_run_output(path: Path, rho: float) -> TGLFOutput:
    """Parse the human-readable GACODE run summary into signed raw fluxes."""
    particle_e = 0.0
    particle_i = 0.0
    q_e = 0.0
    q_i = 0.0
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        tokens = line.split()
        if len(tokens) < 3:
            continue
        try:
            particle_flux = float(tokens[1])
            energy_flux = float(tokens[2])
        except ValueError:
            continue
        if not (math.isfinite(particle_flux) and math.isfinite(energy_flux)):
            continue
        if tokens[0].lower() == "elec":
            particle_e = particle_flux
            q_e = energy_flux
        elif tokens[0].lower() == "ion1":
            particle_i = particle_flux
            q_i = energy_flux
    return TGLFOutput(
        rho=rho,
        q_i=q_i,
        q_e=q_e,
        particle_e=particle_e,
        particle_i=particle_i,
    )
