# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — TGLF Interface Runtime
"""Runtime subprocess helpers for the public TGLF interface."""

from __future__ import annotations

import logging
import math
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from scpn_fusion.core._tglf_interface_types import (
    TGLFInputDeck,
    TGLFOutput,
    _TGLF_MAX_RETRIES_LIMIT,
    _TGLF_RETRY_BACKOFF_SECONDS,
)

logger = logging.getLogger(__name__)


def _normalize_tglf_timeout_seconds(timeout_s: float) -> float:
    timeout = float(timeout_s)
    if not math.isfinite(timeout) or timeout <= 0.0:
        raise ValueError("timeout_s must be finite and > 0.")
    return timeout


def _normalize_tglf_max_retries(max_retries: int) -> int:
    if isinstance(max_retries, bool) or not isinstance(max_retries, int):
        raise ValueError(f"max_retries must be an integer in [0, {_TGLF_MAX_RETRIES_LIMIT}].")
    retries = int(max_retries)
    if retries < 0 or retries > _TGLF_MAX_RETRIES_LIMIT:
        raise ValueError(f"max_retries must be an integer in [0, {_TGLF_MAX_RETRIES_LIMIT}].")
    return retries


def write_tglf_input_file(deck: TGLFInputDeck, output_dir: str | Path) -> Path:
    """Write a TGLF input.tglf file from a TGLFInputDeck."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "input.tglf"

    lines = [
        "# TGLF input deck generated by SCPN Fusion Core",
        f"# rho = {deck.rho:.4f}",
        "SIGN_BT = 1.0",
        "SIGN_IT = 1.0",
        "NS = 2",
        "MASS_1 = 2.0",
        "MASS_2 = 1.0",
        "ZS_1 = 1.0",
        "ZS_2 = -1.0",
        f"RLNS_1 = {deck.R_Lni:.6f}",
        f"RLNS_2 = {deck.R_Lne:.6f}",
        f"RLTS_1 = {deck.R_LTi:.6f}",
        f"RLTS_2 = {deck.R_LTe:.6f}",
        "TAUS_1 = 1.0",
        f"TAUS_2 = {deck.T_e_keV / max(deck.T_i_keV, 0.01):.6f}",
        "AS_1 = 1.0",
        "AS_2 = 1.0",
        f"Q_LOC = {deck.q:.6f}",
        f"Q_PRIME_LOC = {deck.q_prime_loc:.6f}",
        f"P_PRIME_LOC = {deck.p_prime_loc:.6f}",
        f"S_KAPPA_LOC = {deck.s_kappa:.6f}",
        f"S_DELTA_LOC = {deck.s_delta:.6f}",
        f"KAPPA_LOC = {deck.kappa:.6f}",
        f"DELTA_LOC = {deck.delta:.6f}",
        f"SHAT_LOC = {deck.s_hat:.6f}",
        f"ALPHA_LOC = {deck.alpha_mhd:.6f}",
        f"XNUE = {deck.xnue:.6f}",
        f"BETAE = {deck.beta_e:.6f}",
        f"ZEFF = {deck.Z_eff:.6f}",
        f"RMAJ_LOC = {deck.R_major:.6f}",
        f"RMIN_LOC = {deck.a_minor * deck.rho:.6f}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def run_tglf_binary(
    deck: TGLFInputDeck,
    tglf_binary_path: str | Path,
    *,
    timeout_s: float = 120.0,
    work_dir: str | Path | None = None,
    max_retries: int = 2,
) -> TGLFOutput:
    """Execute the TGLF binary on a given input deck and parse output."""
    timeout_s = _normalize_tglf_timeout_seconds(timeout_s)
    max_retries = _normalize_tglf_max_retries(max_retries)
    tglf_path = Path(tglf_binary_path)
    if not tglf_path.exists():
        raise FileNotFoundError(f"TGLF binary not found: {tglf_path}")

    for field_name, val in deck.__dict__.items():
        if isinstance(val, (float, int)) and not np.isfinite(val):
            logger.warning("TGLF input '%s' is non-finite (%s). Clipping.", field_name, val)
            setattr(deck, field_name, 0.0)

    cleanup = False
    if work_dir is None:
        work_dir = Path(tempfile.mkdtemp(prefix="tglf_"))
        cleanup = True
    else:
        work_dir = Path(work_dir)
        work_dir.mkdir(parents=True, exist_ok=True)

    last_exc = None
    for attempt in range(max_retries + 1):
        try:
            write_tglf_input_file(deck, work_dir)
            result = subprocess.run(
                [str(tglf_path)],
                cwd=str(work_dir),
                capture_output=True,
                text=True,
                timeout=timeout_s,
            )

            if result.returncode != 0:
                raise RuntimeError(
                    f"TGLF exited with code {result.returncode}: {result.stderr[:500]}"
                )

            output_file = work_dir / "out.tglf.run"
            if output_file.exists():
                return _parse_tglf_run_output(output_file, deck.rho)

            if (work_dir / "output.json").exists():
                from scpn_fusion.core import tglf_interface as public_tglf

                outputs = public_tglf.parse_tglf_output(work_dir)
                if outputs:
                    return outputs[0]

            raise RuntimeError("TGLF produced no parseable output.")

        except (RuntimeError, subprocess.TimeoutExpired) as exc:
            last_exc = exc
            if attempt < max_retries:
                logger.warning("TGLF attempt %d failed: %s. Retrying...", attempt + 1, exc)
                import time

                time.sleep(_TGLF_RETRY_BACKOFF_SECONDS)
        finally:
            if cleanup and (attempt == max_retries or not last_exc):
                import shutil

                shutil.rmtree(work_dir, ignore_errors=True)

    if last_exc:
        logger.error("TGLF execution failed after %d attempts.", max_retries + 1)
        return TGLFOutput(rho=deck.rho)

    return TGLFOutput(rho=deck.rho)


def _parse_tglf_run_output(path: Path, rho: float) -> TGLFOutput:
    """Parse TGLF's out.tglf.run text output file."""
    chi_i = 0.0
    chi_e = 0.0
    gamma_max = 0.0

    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        line = line.strip()
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip().upper()
        val = val.strip()
        try:
            parsed = float(val)
        except ValueError:
            continue
        if not np.isfinite(parsed):
            continue
        fval = float(parsed)
        if key == "CHI_I" or key == "CHIEFF_I":
            chi_i = fval
        elif key == "CHI_E" or key == "CHIEFF_E":
            chi_e = fval
        elif key == "GAMMA_MAX":
            gamma_max = fval

    return TGLFOutput(rho=rho, chi_i=chi_i, chi_e=chi_e, gamma_max=gamma_max)
