# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — Shaped-Geometry Ballooning Second-Stability Reference
"""Shaped-geometry ballooning-critical-alpha reference with second-stability access.

Consumes the committed pyrokinetics reference artifact (generated by
:mod:`validation.ballooning_reference_runner` in the dedicated
``.venv-pyrokinetics`` environment) and provides the ideal-ballooning critical
normalised pressure gradient ``alpha_crit`` as a function of pedestal magnetic
shear for the shaped (Miller) DIII-D geometry.

Unlike the reduced circular s-alpha first-stability boundary
(:func:`scpn_fusion.core.ballooning_solver.find_marginal_stability`), the
shaped reference resolves the *second-stability access* that real pedestals
exploit: at low shear (and under the pedestal Shafranov shift) the surface stays
stable to the full scanned drive, so the ballooning constraint no longer caps
the pedestal — it becomes peeling-limited. Second-stability rows are represented
by the scan ceiling ``alpha_max``, which drives the coupled peeling-ballooning
boundary onto its current limit.

This keeps the main-venv consumer hermetic: it reads the committed JSON, never
pyrokinetics, so the pedestal comparison lane is deterministic against the
audited artifact.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import numpy as np

ARTIFACT_SCHEMA = "scpn-fusion-core.pyrokinetics-ballooning-alpha-crit.v1"

_DEFAULT_REFERENCE = (
    Path(__file__).resolve().parents[3]
    / "validation"
    / "reference_data"
    / "ballooning"
    / "pyrokinetics_alpha_crit.json"
)


@dataclass(frozen=True)
class BallooningSecondStabilityReference:
    """Shaped ideal-ballooning ``alpha_crit`` vs magnetic shear.

    Second-stability rows (no finite boundary up to the scan ceiling) are stored
    at their ``alpha_max`` ceiling so interpolation and the downstream peeling-
    ballooning coupling see a large-but-finite critical gradient.
    """

    shear: tuple[float, ...]
    alpha_crit: tuple[float, ...]
    second_stability_access: tuple[bool, ...]
    shaping: Mapping[str, Any]
    provenance: Mapping[str, Any]

    @classmethod
    def from_artifact(cls, path: str | Path | None = None) -> BallooningSecondStabilityReference:
        """Load and validate the committed reference artifact.

        Parameters
        ----------
        path : str or Path, optional
            Artifact location; defaults to the committed DIII-D reference.

        Returns
        -------
        BallooningSecondStabilityReference
            Parsed, shear-sorted reference.

        Raises
        ------
        FileNotFoundError
            If the artifact is absent (the heavy pyrokinetics run has not been
            committed yet).
        ValueError
            On a foreign schema or an empty / malformed table.
        """
        artifact_path = Path(path) if path is not None else _DEFAULT_REFERENCE
        if not artifact_path.is_file():
            raise FileNotFoundError(
                f"ballooning reference artifact not found: {artifact_path}. "
                "Generate it with validation/ballooning_reference_runner.py "
                "inside .venv-pyrokinetics."
            )
        payload = json.loads(artifact_path.read_text(encoding="utf-8"))
        return cls.from_payload(payload)

    @classmethod
    def from_payload(cls, payload: Mapping[str, Any]) -> BallooningSecondStabilityReference:
        """Build the reference from an already-parsed artifact payload."""
        if not isinstance(payload, Mapping) or payload.get("schema") != ARTIFACT_SCHEMA:
            raise ValueError("unexpected ballooning reference schema")
        rows = payload.get("diiid_alpha_crit")
        if not isinstance(rows, list) or len(rows) == 0:
            raise ValueError("reference must carry a non-empty diiid_alpha_crit table")

        ordered = sorted(rows, key=lambda r: float(r["shat"]))
        shear: list[float] = []
        alpha_crit: list[float] = []
        second: list[bool] = []
        for row in ordered:
            access = bool(row["second_stability_access"])
            if access:
                crit = float(row["alpha_max"])
            else:
                crit_value = row["alpha_crit"]
                if crit_value is None:
                    raise ValueError("first-stability row must carry a finite alpha_crit")
                crit = float(crit_value)
            shear.append(float(row["shat"]))
            alpha_crit.append(crit)
            second.append(access)

        return cls(
            shear=tuple(shear),
            alpha_crit=tuple(alpha_crit),
            second_stability_access=tuple(second),
            shaping=dict(payload.get("diiid_shaping", {})),
            provenance=dict(payload.get("provenance", {})),
        )

    def alpha_crit_at(self, shat: float) -> float:
        """Interpolated ideal-ballooning critical alpha at ``shat``.

        Linear interpolation over the shear grid, clamped to the grid endpoints
        (constant extrapolation outside the sampled range).

        Parameters
        ----------
        shat : float
            Pedestal magnetic shear.

        Returns
        -------
        float
            Critical normalised pressure gradient; the scan ceiling where the
            shear sits inside a second-stability window.
        """
        s = float(shat)
        xs = np.asarray(self.shear, dtype=np.float64)
        ys = np.asarray(self.alpha_crit, dtype=np.float64)
        return float(np.interp(s, xs, ys))

    def has_second_stability_at(self, shat: float) -> bool:
        """Whether ``shat`` falls on a second-stability-access grid row.

        Uses nearest-neighbour classification on the discrete grid: the boolean
        access flag is not interpolable, so the closest sampled shear decides.
        """
        s = float(shat)
        idx = int(np.argmin(np.abs(np.asarray(self.shear, dtype=np.float64) - s)))
        return bool(self.second_stability_access[idx])
