#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Fusion Core — TORAX Same-Physics Configuration Study
"""Evaluate the TORAX/native transport same-physics configuration boundary."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence, cast

import numpy as np
import numpy.typing as npt

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
REFERENCE = ROOT / "validation" / "reference_data" / "torax" / "torax_basic_config_profiles.json"
NATIVE_CONFIG = ROOT / "validation" / "iter_config.json"
REPORT_JSON = ROOT / "validation" / "reports" / "torax_same_physics_config_study.json"
REPORT_MD = ROOT / "validation" / "reports" / "torax_same_physics_config_study.md"
SCHEMA = "scpn-fusion-core.torax-same-physics-config-study.v1"
PROBE_DT_S = 1.0e-3
PROBE_P_AUX_MW = 0.0
CONFINEMENT_REFERENCE_POWER_MW = 50.0

sys.path.insert(0, str(SRC))

from scpn_fusion.core.integrated_transport_solver import TransportSolver  # noqa: E402

FloatArray = npt.NDArray[np.float64]


def _checksum(payload: Mapping[str, Any]) -> str:
    """Return a deterministic checksum for JSON-compatible mappings."""
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _array_checksum(values: FloatArray) -> str:
    """Return a deterministic checksum for a floating-point array."""
    canonical = json.dumps(values.tolist(), separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def _finite_float_list(name: str, raw: object) -> list[float]:
    """Coerce a JSON vector to a finite float list."""
    if isinstance(raw, (str, bytes)) or not isinstance(raw, Sequence):
        raise ValueError(f"{name} must be a sequence.")
    values = [float(value) for value in raw]
    if len(values) < 2:
        raise ValueError(f"{name} must contain at least 2 values.")
    if not np.all(np.isfinite(np.asarray(values, dtype=np.float64))):
        raise ValueError(f"{name} must contain only finite values.")
    return values


def load_torax_reference(path: Path = REFERENCE) -> dict[str, Any]:
    """Load the tracked TORAX reference profile artifact.

    Parameters
    ----------
    path:
        TORAX JSON profile artifact generated by ``torax_reference_runner.py``.

    Returns
    -------
    dict[str, Any]
        Validated reference artifact.
    """
    payload = cast(dict[str, Any], json.loads(path.read_text(encoding="utf-8")))
    if payload.get("schema") != "scpn-fusion-core.torax-reference-profiles.v1":
        raise ValueError("TORAX reference artifact has an unexpected schema.")
    provenance = payload.get("provenance")
    if not isinstance(provenance, Mapping) or provenance.get("code") != "TORAX":
        raise ValueError("TORAX reference artifact must carry TORAX provenance.")
    profiles = payload.get("profiles")
    if not isinstance(profiles, Mapping):
        raise ValueError("TORAX reference artifact must contain profile data.")
    required = ("rho_norm", "T_e_keV", "T_i_keV", "n_e_m3")
    missing = [key for key in required if key not in profiles]
    if missing:
        raise ValueError(f"TORAX reference profiles missing keys: {missing}")
    lengths = {key: len(_finite_float_list(f"profiles.{key}", profiles[key])) for key in required}
    if len(set(lengths.values())) != 1:
        raise ValueError(f"TORAX reference profile lengths are misaligned: {lengths}")
    rho = _finite_float_list("profiles.rho_norm", profiles["rho_norm"])
    if any(next_value <= value for value, next_value in zip(rho, rho[1:])):
        raise ValueError("profiles.rho_norm must be strictly increasing.")
    return payload


def reference_profiles(reference: Mapping[str, Any]) -> dict[str, FloatArray]:
    """Return TORAX profiles in native transport-solver units."""
    profiles = cast(Mapping[str, Any], reference["profiles"])
    return {
        "rho_norm": np.asarray(
            _finite_float_list("profiles.rho_norm", profiles["rho_norm"]), dtype=np.float64
        ),
        "T_e_keV": np.asarray(
            _finite_float_list("profiles.T_e_keV", profiles["T_e_keV"]), dtype=np.float64
        ),
        "T_i_keV": np.asarray(
            _finite_float_list("profiles.T_i_keV", profiles["T_i_keV"]), dtype=np.float64
        ),
        "n_e_1e19_m3": np.asarray(
            _finite_float_list("profiles.n_e_m3", profiles["n_e_m3"]), dtype=np.float64
        )
        / 1.0e19,
    }


def initialise_native_solver_from_torax(
    reference: Mapping[str, Any],
    *,
    config_path: Path = NATIVE_CONFIG,
) -> TransportSolver:
    """Initialize the native transport solver from TORAX final profiles."""
    profiles = reference_profiles(reference)
    rho = profiles["rho_norm"]
    solver = TransportSolver(config_path)
    solver.rho = rho.copy()
    solver.nr = int(rho.size)
    solver.drho = float(np.mean(np.diff(rho)))
    solver.Te = profiles["T_e_keV"].copy()
    solver.Ti = profiles["T_i_keV"].copy()
    solver.ne = profiles["n_e_1e19_m3"].copy()
    solver.chi_e = np.ones(solver.nr, dtype=np.float64)
    solver.chi_i = np.ones(solver.nr, dtype=np.float64)
    solver.D_n = np.ones(solver.nr, dtype=np.float64)
    solver.n_impurity = np.zeros(solver.nr, dtype=np.float64)
    solver.T_edge_keV = float(solver.Te[-1])
    return solver


def _profile_summary(values: FloatArray) -> dict[str, Any]:
    """Summarise a finite profile for the report."""
    return {
        "count": int(values.size),
        "core": float(values[0]),
        "edge": float(values[-1]),
        "minimum": float(np.min(values)),
        "maximum": float(np.max(values)),
        "checksum_sha256": _array_checksum(values),
    }


def _component_rows(native_model: str) -> list[dict[str, Any]]:
    """Describe which TORAX/native configuration components are actually shared."""
    return [
        {
            "component": "radial_grid",
            "status": "shared_ready",
            "evidence": "TORAX rho_norm copied into native solver rho grid.",
            "blocks_threshold_tightening": False,
        },
        {
            "component": "initial_profiles",
            "status": "shared_ready",
            "evidence": "TORAX Te, Ti, and ne copied into native solver units.",
            "blocks_threshold_tightening": False,
        },
        {
            "component": "native_transport_model",
            "status": "blocked_model_mismatch",
            "evidence": f"Native update uses {native_model}; TORAX transport-model internals are not in the artifact.",
            "blocks_threshold_tightening": True,
        },
        {
            "component": "sources_and_boundary_conditions",
            "status": "blocked_missing_same_deck_controls",
            "evidence": "The tracked TORAX artifact contains final profiles and config SHA, not source terms, boundary controls, or a native-compatible input deck.",
            "blocks_threshold_tightening": True,
        },
        {
            "component": "time_integration_contract",
            "status": "blocked_missing_same_step_trace",
            "evidence": "No redistributable TORAX step-by-step state trace is tracked for matching native one-step or trajectory thresholds.",
            "blocks_threshold_tightening": True,
        },
    ]


def build_report(
    *,
    reference_path: Path = REFERENCE,
    config_path: Path = NATIVE_CONFIG,
) -> dict[str, Any]:
    """Build the TORAX/native same-physics configuration study report."""
    reference = load_torax_reference(reference_path)
    profiles = reference_profiles(reference)
    solver = initialise_native_solver_from_torax(reference, config_path=config_path)

    initial_te = solver.Te.copy()
    initial_ti = solver.Ti.copy()
    initial_ne = solver.ne.copy()
    finite_initial_state = bool(
        np.all(np.isfinite(initial_te))
        and np.all(np.isfinite(initial_ti))
        and np.all(np.isfinite(initial_ne))
    )
    confinement_time_s = float(solver.compute_confinement_time(CONFINEMENT_REFERENCE_POWER_MW))
    solver.update_transport_model(CONFINEMENT_REFERENCE_POWER_MW)
    native_model = str(solver._last_transport_closure_contract.get("model", "unknown"))
    chi_e_mean = float(np.mean(solver.chi_e))
    chi_i_mean = float(np.mean(solver.chi_i))
    step_balance = solver.evolve_profiles(PROBE_DT_S, PROBE_P_AUX_MW)
    finite_after_probe = bool(np.all(np.isfinite(solver.Te)) and np.all(np.isfinite(solver.Ti)))
    component_rows = _component_rows(native_model)
    threshold_blockers = [
        row["component"] for row in component_rows if bool(row["blocks_threshold_tightening"])
    ]

    return {
        "schema": SCHEMA,
        "status": "same_initial_profile_config_ready_thresholds_blocked",
        "passes_thresholds": True,
        "same_physics_ready": False,
        "threshold_tightening_ready": False,
        "physics_equivalence_claimed": False,
        "claim_boundary": (
            "This study proves the TORAX final profiles can initialize the native transport "
            "solver and identifies the remaining same-physics blockers. It does not claim "
            "TORAX/native physics equivalence."
        ),
        "reference": {
            "artifact": str(reference_path.relative_to(ROOT)),
            "profile_checksum_sha256": _checksum(cast(Mapping[str, Any], reference["profiles"])),
            "provenance": reference["provenance"],
            "final_time_s": float(reference["final_time_s"]),
        },
        "native_solver": {
            "config": str(config_path.relative_to(ROOT)),
            "profile_count": int(solver.nr),
            "drho_mean": float(solver.drho),
            "finite_initial_state": finite_initial_state,
            "finite_after_probe": finite_after_probe,
            "transport_model_after_update": native_model,
            "chi_e_mean_after_update": chi_e_mean,
            "chi_i_mean_after_update": chi_i_mean,
            "confinement_time_at_50mw_s": confinement_time_s,
            "one_step_probe": {
                "dt_s": PROBE_DT_S,
                "p_aux_mw": PROBE_P_AUX_MW,
                "energy_balance": [float(value) for value in step_balance],
                "core_te_after_step_keV": float(solver.Te[0]),
                "core_ti_after_step_keV": float(solver.Ti[0]),
                "core_te_delta_keV": float(solver.Te[0] - initial_te[0]),
                "core_ti_delta_keV": float(solver.Ti[0] - initial_ti[0]),
            },
        },
        "profile_summaries": {
            "rho_norm": _profile_summary(profiles["rho_norm"]),
            "T_e_keV": _profile_summary(profiles["T_e_keV"]),
            "T_i_keV": _profile_summary(profiles["T_i_keV"]),
            "n_e_1e19_m3": _profile_summary(profiles["n_e_1e19_m3"]),
        },
        "same_physics_matrix": component_rows,
        "threshold_blockers": threshold_blockers,
    }


def render_markdown(report: Mapping[str, Any]) -> str:
    """Render the same-physics configuration report as Markdown."""
    native = cast(Mapping[str, Any], report["native_solver"])
    lines = [
        "# TORAX Same-Physics Configuration Study",
        "",
        f"Status: `{report['status']}`",
        f"Same-physics ready: `{report['same_physics_ready']}`",
        f"Threshold tightening ready: `{report['threshold_tightening_ready']}`",
        f"Physics equivalence claimed: `{report['physics_equivalence_claimed']}`",
        "",
        str(report["claim_boundary"]),
        "",
        "## Native Solver Probe",
        "",
        f"- Config: `{native['config']}`",
        f"- Profile points: `{native['profile_count']}`",
        f"- Transport model after update: `{native['transport_model_after_update']}`",
        f"- Finite initial state: `{native['finite_initial_state']}`",
        f"- Finite after one-step probe: `{native['finite_after_probe']}`",
        "",
        "## Same-Physics Matrix",
        "",
        "| Component | Status | Blocks threshold tightening | Evidence |",
        "|---|---|---:|---|",
    ]
    for row in cast(Sequence[Mapping[str, Any]], report["same_physics_matrix"]):
        lines.append(
            f"| `{row['component']}` | `{row['status']}` | `{row['blocks_threshold_tightening']}` | {row['evidence']} |"
        )
    lines.extend(["", "## Threshold Blockers", ""])
    for blocker in cast(Sequence[str], report["threshold_blockers"]):
        lines.append(f"- `{blocker}`")
    lines.append("")
    return "\n".join(lines)


def write_report(
    *,
    reference_path: Path = REFERENCE,
    config_path: Path = NATIVE_CONFIG,
    report_json: Path = REPORT_JSON,
    report_md: Path = REPORT_MD,
) -> dict[str, Any]:
    """Write the same-physics study JSON and Markdown reports."""
    report = build_report(reference_path=reference_path, config_path=config_path)
    report_json.parent.mkdir(parents=True, exist_ok=True)
    report_json.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_md.write_text(render_markdown(report), encoding="utf-8")
    return report


def check_report(
    *,
    reference_path: Path = REFERENCE,
    config_path: Path = NATIVE_CONFIG,
    report_json: Path = REPORT_JSON,
    report_md: Path = REPORT_MD,
) -> list[str]:
    """Return drift errors for the tracked same-physics study reports."""
    expected = build_report(reference_path=reference_path, config_path=config_path)
    expected_md = render_markdown(expected)
    errors: list[str] = []
    if not report_json.exists():
        errors.append(f"missing same-physics JSON report: {report_json}")
    else:
        observed = cast(Mapping[str, Any], json.loads(report_json.read_text(encoding="utf-8")))
        if _checksum(observed) != _checksum(expected):
            errors.append("tracked same-physics JSON report is stale")
    if not report_md.exists():
        errors.append(f"missing same-physics Markdown report: {report_md}")
    elif report_md.read_text(encoding="utf-8") != expected_md:
        errors.append("tracked same-physics Markdown report is stale")
    return errors


def main(argv: list[str] | None = None) -> int:
    """Run or check the TORAX/native same-physics configuration study."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=REFERENCE)
    parser.add_argument("--config", type=Path, default=NATIVE_CONFIG)
    parser.add_argument("--report-json", type=Path, default=REPORT_JSON)
    parser.add_argument("--report-md", type=Path, default=REPORT_MD)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    if args.check:
        errors = check_report(
            reference_path=args.reference,
            config_path=args.config,
            report_json=args.report_json,
            report_md=args.report_md,
        )
        for error in errors:
            print(f"TORAX SAME-PHYSICS CONFIG ERROR: {error}", file=sys.stderr)
        if errors:
            return 1
        print(f"TORAX same-physics config reports are up to date: {args.report_json}")
        return 0

    report = write_report(
        reference_path=args.reference,
        config_path=args.config,
        report_json=args.report_json,
        report_md=args.report_md,
    )
    print(json.dumps(report["native_solver"], indent=2, sort_keys=True))
    print(f"status: {report['status']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
