#!/usr/bin/env python
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
"""Generate docs/PSI_GATE_ATTRIBUTION.md from the ψ_N EFIT-NRMSE gate report.

Publishes the per-file attribution of the intentionally failing 18-file ψ_N
reconstruction gate as the honest public boundary (master-plan F-1): which
files fail, why (source-domain residual class), what solver each file requires,
and the shared free-boundary input blocker. Only stable attribution fields are
rendered — per-run timings never reach the document.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = REPO_ROOT / "validation" / "reports" / "psi_efit_nrmse_benchmark.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "PSI_GATE_ATTRIBUTION.md"
REPORT_SCHEMA = "efit-nrmse-benchmark.v2"

_ROW_FIELDS = (
    "file",
    "machine",
    "psi_rmse_norm",
    "adapted_profile_psi_rmse_norm",
    "source_domain_residual_class",
    "source_domain_required_solver_mode",
    "source_domain_next_action",
    "free_boundary_reconstruction_blocker",
)


def load_report(path: Path) -> dict[str, Any]:
    """Load and validate the ψ_N gate benchmark report.

    Args:
        path: Filesystem path to ``psi_efit_nrmse_benchmark.json``.

    Returns:
        Parsed report payload.

    Raises:
        ValueError: If the schema is foreign or required fields are missing.
    """
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("gate report must be a JSON object")
    if payload.get("schema_version") != REPORT_SCHEMA:
        raise ValueError(f"unexpected gate report schema: {payload.get('schema_version')!r}")
    rows = payload.get("rows")
    if not isinstance(rows, list) or len(rows) == 0:
        raise ValueError("gate report must carry a non-empty 'rows' list")
    for i, row in enumerate(rows):
        if not isinstance(row, dict):
            raise ValueError(f"rows[{i}] must be an object")
        missing = [field for field in _ROW_FIELDS if field not in row]
        if missing:
            raise ValueError(f"rows[{i}] is missing attribution fields: {missing}")
    return payload


def _fmt_pct(value: float) -> str:
    number = float(value)
    if number != number:  # NaN: lane not applicable for this file
        return "—"
    return f"{100.0 * number:.1f}%"


def _counts_table(title: str, counts: dict[str, Any]) -> list[str]:
    lines = ["", f"### {title}", "", "| Class | Files |", "|---|---:|"]
    for key in sorted(counts):
        lines.append(f"| `{key}` | {counts[key]} |")
    return lines


def render_markdown(report: dict[str, Any], report_rel: str) -> str:
    """Render the per-file ψ_N gate attribution as Markdown.

    Args:
        report: Validated gate report payload.
        report_rel: Report path string shown in the generated header.

    Returns:
        Rendered Markdown document as a single string.
    """
    threshold = float(report["threshold"])
    rows = report["rows"]
    lines: list[str] = [
        "<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->",
        "<!-- Generated by tools/generate_psi_gate_attribution.py; do not edit by hand. -->",
        "",
        "# ψ_N Reconstruction Gate — Per-File Attribution",
        "",
        "This is the honest public boundary of the bundled EFIT-style ψ_N",
        "reconstruction gate: the gate is **intentionally reported failing** and",
        "stays fail-closed until the attributed blockers below are resolved.",
        "EFIT-grade inverse reconstruction is **not** claimed.",
        "",
        f"- Source report: `{report_rel}`",
        f"- Scope: `{report['benchmark_scope']}`",
        f"- Files: `{report['count']}` "
        f"(by machine: {', '.join(f'{k}={v}' for k, v in sorted(report['count_by_machine'].items()))})",
        f"- Threshold: ψ_N RMSE < {_fmt_pct(threshold)} per file",
        f"- Raw profile-source passes: `{report['pass_count']}/{report['count']}`",
        f"- Convention-adapted profile passes: "
        f"`{report['adapted_profile_pass_count']}/{report['count']}`",
        f"- Gate verdict: `{'PASS' if report['passes'] else 'FAIL (fail-closed by design)'}`",
        "",
        "## Why the gate fails",
        "",
        "Every bundled GEQDSK lacks the external poloidal-field coil currents",
        "required for a free-boundary vacuum reconstruction, and the majority of",
        "files additionally carry a plasma/vacuum source-domain mismatch between",
        "the declared profile source and the discrete Grad-Shafranov operator",
        "source. Fixed-boundary profile-source resolves neither; the per-file",
        "required solver mode below states what each file needs.",
    ]
    lines.extend(
        _counts_table(
            "Free-boundary input blockers",
            report["free_boundary_reconstruction_blocker_counts"],
        )
    )
    lines.extend(
        _counts_table(
            "Source-domain residual classes",
            report["source_domain_residual_class_counts"],
        )
    )
    lines.extend(
        _counts_table(
            "Required solver modes",
            report["source_domain_required_solver_mode_counts"],
        )
    )
    lines.extend(
        [
            "",
            "## Per-file attribution",
            "",
            "| File | ψ_N RMSE (raw) | ψ_N RMSE (adapted) | Residual class | Required solver mode | Next action |",
            "|---|---:|---:|---|---|---|",
        ]
    )
    for row in sorted(rows, key=lambda r: str(r["file"])):
        lines.append(
            f"| `{row['file']}` | {_fmt_pct(row['psi_rmse_norm'])} | "
            f"{_fmt_pct(row['adapted_profile_psi_rmse_norm'])} | "
            f"`{row['source_domain_residual_class']}` | "
            f"`{row['source_domain_required_solver_mode']}` | "
            f"`{row['source_domain_next_action']}` |"
        )
    lines.extend(
        [
            "",
            "## What flips the gate",
            "",
            "1. Acquire or reconstruct external coil currents for the bundled",
            "   files (all 18 are blocked on"
            " `external_coil_currents_missing_from_geqdsk`), then run the",
            "   free-boundary vacuum reconstruction the per-file solver mode",
            "   requires.",
            "2. Repair the plasma profile-source mismatch where attributed before",
            "   reconstructing the vacuum boundary response.",
            "",
            "Independent solver credibility is established separately by the",
            "Solov'ev analytic-equilibrium suite",
            "(`validation/validate_grad_shafranov_solovev.py`,"
            " report `validation/reports/grad_shafranov_solovev.json`):"
            " the discrete operator and both solver paths converge at second",
            "order to the exact field, so the gate failure above is attributed",
            "to missing reconstruction inputs and source conventions, not to the",
            "elliptic solver.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Render or drift-check the ψ_N gate attribution page.

    Args:
        argv: Optional CLI args. If omitted, reads from process arguments.

    Returns:
        0 on success, 1 when the check mode detects drift or a stale page.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        default=str(DEFAULT_REPORT),
        help="Path to the ψ_N gate benchmark report JSON.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Markdown output path.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if output is stale instead of writing it.",
    )
    args = parser.parse_args(argv)

    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = REPO_ROOT / report_path
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path

    report = load_report(report_path)
    try:
        report_rel = report_path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        report_rel = report_path.as_posix()
    rendered = render_markdown(report, report_rel)

    if args.check:
        if not output_path.exists():
            print(f"Psi gate attribution page missing: {output_path}")
            return 1
        if output_path.read_text(encoding="utf-8") != rendered:
            print(
                "Psi gate attribution page is stale. "
                "Run tools/generate_psi_gate_attribution.py to refresh."
            )
            return 1
        print(f"Psi gate attribution page is up to date: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote psi gate attribution page: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
