# ─────────────────────────────────────────────────────────────────────
# SCPN Fusion Core — FNO Training on QLKNN-Oracle Spatial Data
# © 1998–2026 Miroslav Sotek. All rights reserved.
# ─────────────────────────────────────────────────────────────────────
"""
Train the JAX FNO on (equilibrium, transport_field) spatial pairs
generated by the QLKNN MLP oracle.

Prerequisites
-------------
1. Train MLP:  python tools/train_neural_transport_qlknn.py
2. Gen data:   python tools/generate_fno_qlknn_spatial.py

Usage
-----
    python tools/train_fno_qlknn_spatial.py
    python tools/train_fno_qlknn_spatial.py --epochs 500 --modes 24 --width 128 --n-layers 4
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = REPO_ROOT / "data" / "fno_qlknn_spatial"
DEFAULT_OUTPUT = REPO_ROOT / "weights" / "fno_turbulence_jax.npz"


def _load_spatial_split(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Load a spatial split .npz with secure defaults."""
    with np.load(path, allow_pickle=False) as data:
        if "X" not in data or "Y" not in data:
            raise KeyError(f"{path} missing required NPZ keys: X, Y")
        x = data["X"]
        y = data["Y"]
    return x, y


def _augment_flips(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Augment 2D fields with horizontal and vertical flips (4x data)."""
    aug_x = [x, x[:, ::-1, :], x[:, :, ::-1], x[:, ::-1, ::-1]]
    aug_y = [y, y[:, ::-1, :], y[:, :, ::-1], y[:, ::-1, ::-1]]
    return np.concatenate(aug_x, axis=0), np.concatenate(aug_y, axis=0)


def train_fno(
    data_dir: Path,
    output_path: Path,
    modes: int = 24,
    width: int = 128,
    n_layers: int = 4,
    epochs: int = 1500,
    lr: float = 5e-4,
    batch_size: int = 32,
    seed: int = 42,
) -> None:
    """Train FNO on spatial transport data.

    Architecture: Li et al. 2021 "Fourier Neural Operator" with
    n_layers spectral convolution blocks, each with skip connection.
    """
    import jax
    import jax.numpy as jnp
    from jax import random, grad, jit, vmap

    devices = jax.devices()
    gpu = any(d.platform == "gpu" for d in devices)
    print(f"JAX backend: {'GPU' if gpu else 'CPU'} ({devices[0]})")

    if not gpu:
        jax.config.update("jax_platform_name", "cpu")

    for split in ("train.npz", "val.npz"):
        p = data_dir / split
        if not p.exists():
            print(f"ERROR: {p} not found.")
            print("Run first: python tools/generate_fno_qlknn_spatial.py")
            sys.exit(1)

    train_x, train_y = _load_spatial_split(data_dir / "train.npz")
    val_x, val_y = _load_spatial_split(data_dir / "val.npz")

    # Flip augmentation on training data (4x effective samples)
    train_x, train_y = _augment_flips(train_x, train_y)
    n_raw = len(train_x) // 4
    print(f"Data: {n_raw} raw + flip augmentation = {len(train_x)} train, {len(val_x)} val")

    X_train = jnp.array(train_x)
    Y_train = jnp.array(train_y)
    X_val = jnp.array(val_x)
    Y_val = jnp.array(val_y)

    grid_size = X_train.shape[1]
    n_train = len(X_train)
    print(f"  Grid: {grid_size}x{grid_size}")
    print(f"FNO: {n_layers} spectral layers, modes={modes}, width={width}")

    key = random.PRNGKey(seed)

    # Xavier-scale for spectral weights: 1/sqrt(width * modes^2)
    spec_scale = 1.0 / np.sqrt(width * modes * modes)

    def init_params(key):
        keys = random.split(key, 4 + 4 * n_layers)
        ki = 0
        p = {
            "lift_w": random.normal(keys[ki], (1, width)) * 0.1,
            "lift_b": jnp.zeros(width),
        }
        ki += 1
        for i in range(n_layers):
            p[f"w{i}_real"] = random.normal(keys[ki], (width, width, modes, modes)) * spec_scale
            ki += 1
            p[f"w{i}_imag"] = random.normal(keys[ki], (width, width, modes, modes)) * spec_scale
            ki += 1
            p[f"b{i}"] = jnp.zeros(width)
            p[f"skip{i}"] = random.normal(keys[ki], (width, width)) * (1.0 / np.sqrt(width))
            ki += 1
        p["fc1"] = random.normal(keys[ki], (width, 128)) * (1.0 / np.sqrt(width))
        p["fc1_b"] = jnp.zeros(128)
        ki += 1
        p["fc2"] = random.normal(keys[ki], (128, 1)) * (1.0 / np.sqrt(128))
        p["fc2_b"] = jnp.zeros(1)
        return p

    params = init_params(key)

    @jit
    def fno_forward(params, x):
        """Li et al. 2021 FNO: lift -> N spectral conv blocks -> project."""
        x = x[..., None]
        h = x @ params["lift_w"] + params["lift_b"]

        M = modes
        for i in range(n_layers):
            h_fft = jnp.fft.rfft2(h, axes=(0, 1))
            h_low = h_fft[:M, :M, :]
            w_c = params[f"w{i}_real"] + 1j * params[f"w{i}_imag"]
            out_low = jnp.einsum("xyi,ioxy->xyo", h_low, w_c[:, :, :M, :M], optimize=True)
            out_fft = jnp.zeros_like(h_fft).at[:M, :M, :].set(out_low)
            h_spec = jnp.fft.irfft2(out_fft, s=(grid_size, grid_size), axes=(0, 1))
            h_skip = h @ params[f"skip{i}"]
            h = jax.nn.gelu(h_spec + h_skip + params[f"b{i}"])

        h = jax.nn.relu(h @ params["fc1"] + params["fc1_b"])
        h = jax.nn.softplus(h @ params["fc2"] + params["fc2_b"])
        return h.squeeze(-1)

    @jit
    def loss_fn(params, x_batch, y_batch):
        preds = vmap(lambda xi: fno_forward(params, xi))(x_batch)
        diff_sq = jnp.sum((preds - y_batch) ** 2, axis=(1, 2))
        norm_sq = jnp.sum(y_batch ** 2, axis=(1, 2))
        return jnp.mean(jnp.sqrt(diff_sq / jnp.maximum(norm_sq, 1e-8)))

    @jit
    def relative_l2_metric(params, x, y):
        preds = vmap(lambda xi: fno_forward(params, xi))(x)
        return jnp.sqrt(
            jnp.sum((preds - y) ** 2) / jnp.maximum(jnp.sum(y ** 2), 1e-8)
        )

    grad_fn = jit(grad(loss_fn))

    # Adam (standard betas: 0.9, 0.999)
    adam_m = {k: jnp.zeros_like(v) for k, v in params.items()}
    adam_v = {k: jnp.zeros_like(v) for k, v in params.items()}
    t = 0

    best_val = float("inf")
    best_params = None
    patience_counter = 0
    PATIENCE = 100
    n_batches = max(1, n_train // batch_size)
    t0 = time.monotonic()

    for epoch in range(epochs):
        # Cosine annealing with warm restarts not needed; simple cosine
        lr_t = lr * 0.5 * (1 + np.cos(np.pi * epoch / epochs))

        key, sk = random.split(key)
        perm = random.permutation(sk, n_train)
        X_shuf = X_train[perm]
        Y_shuf = Y_train[perm]

        epoch_loss = 0.0
        for b in range(n_batches):
            x_b = X_shuf[b * batch_size:(b + 1) * batch_size]
            y_b = Y_shuf[b * batch_size:(b + 1) * batch_size]

            grads = grad_fn(params, x_b, y_b)
            t += 1

            for k in params:
                g = jnp.clip(grads[k], -1.0, 1.0)
                adam_m[k] = 0.9 * adam_m[k] + 0.1 * g
                adam_v[k] = 0.999 * adam_v[k] + 0.001 * g ** 2
                m_hat = adam_m[k] / (1 - 0.9 ** t)
                v_hat = adam_v[k] / (1 - 0.999 ** t)
                params[k] = params[k] - lr_t * m_hat / (jnp.sqrt(v_hat) + 1e-8)

            epoch_loss += float(loss_fn(params, x_b, y_b))
        epoch_loss /= n_batches

        val_l2 = float(relative_l2_metric(params, X_val, Y_val))
        if val_l2 < best_val:
            best_val = val_l2
            best_params = {k: np.array(v) for k, v in params.items()}
            patience_counter = 0
        else:
            patience_counter += 1

        if epoch % 20 == 0 or epoch == epochs - 1:
            elapsed = time.monotonic() - t0
            print(f"  Epoch {epoch:4d}/{epochs} | "
                  f"train_rel_l2={epoch_loss:.4f} | val_rel_l2={val_l2:.4f} | "
                  f"best={best_val:.4f} | lr={lr_t:.2e} | {elapsed:.0f}s")
            sys.stdout.flush()

        if patience_counter >= PATIENCE and epoch > 200:
            print(f"  Early stop at epoch {epoch} (no improvement for {PATIENCE} epochs)")
            break

    print(f"\nTraining complete. Best val relative L2: {best_val:.4f}")

    # Verification gate — spatial FNO inherits QLKNN oracle noise plus
    # interpolation error, so gate is looser than the point-wise MLP gate.
    SPATIAL_GATE = 0.40
    print("\n=== VERIFICATION GATE ===")
    if best_val >= SPATIAL_GATE:
        print(f"  FAIL: val_relative_l2 = {best_val:.4f} >= {SPATIAL_GATE}")
        sys.exit(1)
    elif best_val >= 0.20:
        print(f"  WARN: val_relative_l2 = {best_val:.4f} >= 0.20 (acceptable, limited by oracle noise)")
    else:
        print(f"  PASS: val_relative_l2 = {best_val:.4f} < 0.20")

    # Save
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(output_path, **best_params)
    print(f"  Saved weights to {output_path}")

    # Save metrics
    metrics = {
        "val_relative_l2": float(best_val),
        "epochs": epochs,
        "modes": modes,
        "width": width,
        "grid_size": grid_size,
        "n_train": n_train,
        "training_time_s": time.monotonic() - t0,
        "data_source": "QLKNN-MLP oracle spatial pairs",
    }
    metrics_path = output_path.with_suffix(".metrics.json")
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"  Metrics saved to {metrics_path}")
    print("\n=== VERIFICATION PASSED ===")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--modes", type=int, default=24)
    parser.add_argument("--width", type=int, default=128)
    parser.add_argument("--n-layers", type=int, default=4)
    parser.add_argument("--epochs", type=int, default=1500)
    parser.add_argument("--lr", type=float, default=5e-4)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    train_fno(args.data_dir, args.output, args.modes, args.width,
              args.n_layers, args.epochs, args.lr, args.batch_size, args.seed)


if __name__ == "__main__":
    main()
